import os
import json
import logging
from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ── Health endpoint ─────────────────────────────────────────────
@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({"status": "ok"})


# ── Compile endpoint ────────────────────────────────────────────
@app.route('/api/compile', methods=['POST'])
def compile_code():
    data = request.get_json()
    if not data or 'code' not in data:
        return jsonify({"error": "Campo 'code' é obrigatório"}), 400

    code = data['code']

    # TODO: Integrate with simplesc compiler
    # For now, return a mock NASM for valid-looking SIMPLES code
    if not code or not code.strip():
        return jsonify({"success": False, "errors": [
            {"line": 0, "column": 0, "message": "Código vazio", "phase": "parser"}
        ]})

    lines = code.strip().split('\n')
    if not any('programa' in line for line in lines):
        return jsonify({"success": False, "errors": [
            {"line": 1, "column": 1, "message": "Programa deve começar com 'programa'", "phase": "parser"}
        ]})

    # Mock NASM output
    mock_asm = """; NASM x86 assembly generated by simplesc
; Source: user program

section .data
    msg db 'Hello from Simples!', 10, 0

section .text
    global _start

_start:
    mov eax, 4          ; sys_write
    mov ebx, 1          ; stdout
    mov ecx, msg        ; message
    mov edx, 20         ; length
    int 0x80

    mov eax, 1          ; sys_exit
    xor ebx, ebx        ; exit code 0
    int 0x80
"""

    return jsonify({
        "success": True,
        "asm": mock_asm.strip()
    })


# ── Error parsing endpoint (mock) ───────────────────────────────
def parse_simplesc_error(stderr: str) -> list:
    """Parse simplesc compiler errors into structured format."""
    errors = []
    for line in stderr.split('\n'):
        if ':' in line and ('erro' in line.lower() or 'error' in line.lower()):
            parts = line.split(':')
            if len(parts) >= 3:
                try:
                    line_num = int(parts[0].strip())
                    errors.append({
                        "line": line_num,
                        "column": 1,
                        "message": parts[-1].strip(),
                        "phase": "compiler"
                    })
                except ValueError:
                    pass
    return errors


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8000, debug=True)
