#!/bin/bash
# build_simplesc.sh — Build simplesc from source or create a mock binary
# Called during Docker image build.
# PRD §14.3: Dockerfile must compile simplesc from source.
set -e

SIMPLESC_SRC="${SIMPLESC_SRC_DIR:-/app/simples-compiler}"
INSTALL_PATH="/usr/local/bin/simplesc"

echo "=== Building simplesc compiler ==="

if [ -d "$SIMPLESC_SRC" ] && [ -f "$SIMPLESC_SRC/Makefile" ]; then
    echo "Found simples-compiler source at $SIMPLESC_SRC"
    cd "$SIMPLESC_SRC"
    echo "Running make..."
    make
    if [ -f "$SIMPLESC_SRC/simplesc" ]; then
        cp "$SIMPLESC_SRC/simplesc" "$INSTALL_PATH"
        chmod +x "$INSTALL_PATH"
        echo "simplesc installed from source to $INSTALL_PATH"
    else
        echo "ERROR: make succeeded but simplesc binary not found" >&2
        exit 1
    fi
else
    echo "simples-compiler source not found at $SIMPLESC_SRC"
    echo "Creating mock simplesc for development/demo..."
    cat > "$INSTALL_PATH" << 'MOCKEOF'
#!/bin/bash
# Mock simplesc — generates minimal NASM assembly for demonstration
# Usage: simplesc <source> -o <output>
# When --version is passed, prints version info.

if [ "$1" = "--version" ]; then
    echo "simplesc mock v1.0.0 (development fallback)"
    exit 0
fi

OUTPUT=""
NEXT_IS_OUTPUT=false

for arg in "$@"; do
    if [ "$NEXT_IS_OUTPUT" = true ]; then
        OUTPUT="$arg"
        NEXT_IS_OUTPUT=false
    elif [ "$arg" = "-o" ]; then
        NEXT_IS_OUTPUT=true
    fi
done

if [ -z "$OUTPUT" ]; then
    echo "Error: no output file specified (use -o <output>)" >&2
    exit 1
fi

# Read the source file to generate a contextual mock message
SOURCE_FILE="$1"
CODE_LEN=0
if [ -n "$SOURCE_FILE" ] && [ -f "$SOURCE_FILE" ]; then
    CODE_LEN=$(wc -c < "$SOURCE_FILE" 2>/dev/null || echo 0)
fi

cat > "$OUTPUT" << ASM
; Generated by simplesc (mock — demonstração)
; Source: ${CODE_LEN} bytes
section .data
    hello db 'SIMPLES mock execution', 0xa
    hello_len equ \$ - hello
section .text
    global _start
_start:
    mov eax, 4          ; sys_write
    mov ebx, 1          ; fd = stdout
    mov ecx, hello
    mov edx, hello_len
    int 0x80
    mov eax, 1          ; sys_exit
    xor ebx, ebx        ; exit code 0
    int 0x80
ASM
exit 0
MOCKEOF
    chmod +x "$INSTALL_PATH"
    echo "Mock simplesc installed to $INSTALL_PATH"
fi

echo "=== simplesc build complete ==="
