#cloud-config
package_update: true
package_upgrade: true

write_files:
  - path: /etc/iptables/rules.v4.simples
    content: |
      # Liberar 80/443 — adicionado pelo cloud-init
      -I INPUT 6 -m state --state NEW -p tcp --dport 80  -j ACCEPT
      -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT

runcmd:
  # Liberar firewall do host
  - iptables -I INPUT 6 -m state --state NEW -p tcp --dport 80  -j ACCEPT
  - iptables -I INPUT 6 -m state --state NEW -p tcp --dport 443 -j ACCEPT
  - netfilter-persistent save

  # Docker Engine + Compose v2 (ARM64)
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker ubuntu
